name: ApptainerImage

on:
  workflow_dispatch:
    inputs: 
      finn_use_custom:
        description: 'Use custom commit instead of Xilinx/finn'
        required: true
        default: false
        type: boolean
      finn_owner:
        description: 'finn repository owner to use'
        required: false
        default: 'Xilinx'
      finn_commit:
        description: 'finn repository commit to use'
        required: false
        default: ''
  schedule:
    - cron: '0 2 * * *'

jobs:
  build_docker:
    name: Build Docker image
    runs-on: self-hosted
    outputs:
      finn_sha_short: ${{ steps.get_finn_sha.outputs.sha_short }}
    steps:
      - name: Checkout experiment-manager
        uses: actions/checkout@v3
      - name: Checkout FINN (Xilinx/finn)
        uses: actions/checkout@v3
        with:
          repository: Xilinx/finn
          ref: dev
          path: finn
        if: ${{ !inputs.finn_use_custom }}
      - name: Checkout FINN (custom)
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.finn_owner }}/finn
          ref: ${{ inputs.finn_commit }}
          path: finn
        if: ${{ inputs.finn_use_custom }}
      - name: Set outputs
        id: get_finn_sha
        run: echo "sha_short=$(git -C finn rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build Docker image
        run: cd ./finn && build -f docker/Dockerfile.finn --tag=finn_docker_export .
        shell: bash
        #todo: nocache
        #todo: check if image changed and skip
        #todo: cleanup
  build_apptainer:
    name: Build Apptainer image
    runs-on: self-hosted
    needs: build_docker
    steps:
      - name: Checkout experiment-manager
        uses: actions/checkout@v3
      - name: Build Apptainer image
        run: apptainer build finn_singularity_image.sif docker-daemon://finn_docker_export:latest
        shell: bash
      - name: Clear Apptainer cache
        run: apptainer cache clean
        shell: bash
      - name: Push image to GitHub registry
        run: apptainer push finn_singularity_image.sif oras://ghcr.io/eki-project/experiment-manager/finn_apptainer_xilinx_dev:${{ needs.build_docker.outputs.finn_sha_short }}
        shell: bash
        if: ${{ !inputs.finn_use_custom }}
      - name: Push image to GitHub registry
        run: apptainer push finn_singularity_image.sif oras://ghcr.io/eki-project/experiment-manager/finn_apptainer_${{ inputs.finn_owner }}:${{ needs.build_docker.outputs.finn_sha_short }}
        shell: bash
        if: ${{ inputs.finn_use_custom }}
