name: ApptainerImage

on:
  workflow_dispatch:
    inputs: 
      finn_use_custom:
        description: 'Use custom commit instead of Xilinx/finn/dev'
        required: true
        default: false
        type: boolean
      finn_owner:
        description: 'Custom finn repository owner to use'
        required: false
        default: 'xilinx'
      finn_commit:
        description: 'Custom finn repository commit to use'
        required: false
        default: ''
  schedule:
    - cron: '0 2 * * *'

jobs:
  build_docker:
    name: Build Docker image
    runs-on: self-hosted
    outputs:
      check_not_exists: ${{ steps.check_if_exists.outputs.check_not_exists }}
      finn_sha_short: ${{ steps.get_finn_sha.outputs.finn_sha_short }}
    steps:
      - name: Checkout experiment-manager
        uses: actions/checkout@v3
      - name: Checkout FINN (Xilinx/finn/dev)
        uses: actions/checkout@v3
        with:
          repository: Xilinx/finn
          ref: dev
          path: finn
        if: ${{ !inputs.finn_use_custom }}
      - name: Checkout FINN (custom)
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.finn_owner }}/finn
          ref: ${{ inputs.finn_commit }}
          path: finn
        if: ${{ inputs.finn_use_custom }}
      - name: Get FINN commit hash
        id: get_finn_sha
        run: echo "finn_sha_short=$(git -C finn rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check if image exists
        id: check_if_exists
        run: apptainer pull -F --disable-cache gha_tmp.sif oras://ghcr.io/eki-project/experiment-manager/finn_apptainer_xilinx:${{ steps.get_finn_sha.outputs.finn_sha_short }} ; echo "check_not_exists=$?" >> $GITHUB_OUTPUT
        if: ${{ !inputs.finn_use_custom }}
        continue-on-error: true
      - name: Build Docker image
        run: cd ./finn && docker build --no-cache -f docker/Dockerfile.finn --tag=finn_docker_export .
        shell: bash
        if: ${{ inputs.finn_use_custom || steps.check_if_exists.outputs.check_not_exists != 0 }}
      - name: Clean Docker image cache
        run: echo 'y' | docker image prune
        shell: bash
        if: ${{ inputs.finn_use_custom || steps.check_if_exists.outputs.check_not_exists != 0 }}
      - name: Clean Docker build cache
        run: echo 'y' | docker builder prune
        shell: bash
        if: ${{ inputs.finn_use_custom || steps.check_if_exists.outputs.check_not_exists != 0 }}
  build_apptainer:
    name: Build Apptainer image
    runs-on: self-hosted
    needs: build_docker
    if: ${{ inputs.finn_use_custom || needs.build_docker.outputs.check_not_exists != 0 }}
    steps:
      - name: Checkout experiment-manager
        uses: actions/checkout@v3
      - name: Build Apptainer image
        run: apptainer build finn_singularity_image.sif docker-daemon://finn_docker_export:latest
        shell: bash
      - name: Clear Apptainer cache
        run: echo 'y' | apptainer cache clean
        shell: bash
      - name: Push image to GitHub registry (xilinx)
        run: apptainer push finn_singularity_image.sif oras://ghcr.io/eki-project/experiment-manager/finn_apptainer_xilinx:${{ needs.build_docker.outputs.finn_sha_short }}
        shell: bash
        if: ${{ !inputs.finn_use_custom }}
      - name: Push image to GitHub registry (xilinx, second time to set dev tag)
        run: apptainer push finn_singularity_image.sif oras://ghcr.io/eki-project/experiment-manager/finn_apptainer_xilinx:dev
        shell: bash
        if: ${{ !inputs.finn_use_custom }}
      - name: Push image to GitHub registry (custom)
        run: apptainer push finn_singularity_image.sif oras://ghcr.io/eki-project/experiment-manager/finn_apptainer_${{ inputs.finn_owner }}:${{ needs.build_docker.outputs.finn_sha_short }}
        shell: bash
        if: ${{ inputs.finn_use_custom }}
