name: ApptainerImage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build_docker:
    name: Build Docker image
    runs-on: self-hosted
    steps:
      - name: Checkout experiment-manager
        uses: actions/checkout@v3
      - name: Checkout FINN
        uses: actions/checkout@v3
        with:
          repository: Xilinx/finn
          ref: dev
          path: finn
      - name: Build Docker image
        run: ./experiment-manager/image_build/build_docker_image.sh
        shell: bash
        
  build_apptainer:
    name: Build Apptainer image
    runs-on: self-hosted
    needs: build_docker
    steps:
      - name: Checkout experiment-manager
        uses: actions/checkout@v3
      - name: Build Apptainer image
        run: ./experiment-manager/image_build/build_apptainer_image.sh
        shell: bash
      - name: Distribute Apptainer image
        run: ./experiment-manager/image_build/distribute_image.sh
        shell: bash
